themes/andaze/assets/css/tailwind.css
themes/andaze/layouts/partials/head.html
themes/andaze/layouts/partials/tailwindcss.cdn.html

Nishidai-andaze/issue17

---

themes/andaze/layouts/index.html
themes/andaze/layouts/partials/molecule-article-card.html
themes/andaze/layouts/partials/organism-section-contents.html
themes/andaze/layouts/partials/template-section.html

* https://www.figma.com/file/uDqozBvQAiFg1PqQ9vjwnb/andaze?node-id=21%3A206 の枠組みおよびロジックの作成

Nishidai-andaze/issue23

---

themes/andaze/assets/js/top.js

パーティクルのマウスインタラクション作成

---

themes/andaze/assets/js/top.js
themes/andaze/layouts/partials/top.html

issue#64 ローディングエフェクト

---

themes/andaze/assets/js/top.js

Hatayuki andaze/issue68

---

themes/andaze/assets/js/top.js

Hatayuki-andaze/issue71

---

themes/andaze/assets/js/top.js
themes/andaze/layouts/partials/organism-section-navbar.html
themes/andaze/layouts/partials/top.html

https://github.com/andaze/WebCorporate/issues/77
ローディング表示される範囲の修正
DIPの初期表示のように変更する

Hatayuki andaze/issue77

---

themes/andaze/assets/js/top.js
themes/andaze/layouts/index.html

https://github.com/andaze/WebCorporate/issues/82
ヘッダーのhightが加わった分、キービジュアルが下にずれた。
これによりインタラクションで取得する座標がずれたため調整する。

Hatayuki-andaze/issue82

---

themes/andaze/layouts/index.html
themes/andaze/layouts/partials/atom-irnews-button.html
themes/andaze/layouts/partials/atom-irnews-heading.html
themes/andaze/layouts/partials/molecule-section-irnews-buttongroup.html
themes/andaze/layouts/partials/organism-section-irnews-left.html
themes/andaze/layouts/partials/template-section-irnews.html

Nishidai andaze/issue90

---

themes/andaze/layouts/news/list.html
themes/andaze/layouts/partials/atom-irnews-heading.html
themes/andaze/layouts/partials/template-section.html

Nishidai andaze/issue97

---

themes/andaze/assets/js/top.js

https://github.com/andaze/WebCorporate/issues/109
キービジュアルを自動でアニメーションさせる。
タイマーで発火

Hatayuki-andaze/issue109

---

themes/andaze/layouts/partials/template-section-newtopic.html

To Do
==================
For width issue We update template-section-newtopic.html file 
Add width base on responsive screen

Set responsive width of div for width size issue in new topic slider

---

themes/andaze/layouts/partials/breadcrumbs.html
themes/andaze/layouts/services/list.html
themes/andaze/layouts/services/single.html

Nishidai andaze/issue117

---

themes/andaze/layouts/_default/baseof.html
themes/andaze/layouts/partials/breadcrumbs.html
themes/andaze/layouts/partials/head.html
themes/andaze/layouts/partials/molecule-section-services-tabview.html
themes/andaze/layouts/services/list.html
themes/andaze/layouts/services/single.html

Nishidai andaze/issue121

---

themes/andaze/assets/js/top.js
themes/andaze/layouts/index.html
themes/andaze/layouts/partials/template-section-newtopic.html

https://github.com/andaze/WebCorporate/issues/125

Hatayuki-andaze/issue125

---

themes/andaze/layouts/news/list.html
themes/andaze/layouts/partials/atom-back-to-home-button.html
themes/andaze/layouts/partials/organism-section-news-left.html
themes/andaze/layouts/partials/template-section-news.html

To Do
============================

Nishidai andaze/issue137

---

themes/andaze/layouts/news/list.html
themes/andaze/layouts/partials/atom-back-to-home-button.html
themes/andaze/layouts/partials/atom-irnews-pdf-date.html
themes/andaze/layouts/partials/atom-irnews-pdf-heading.html
themes/andaze/layouts/partials/atom-irnews-pdf-text.html
themes/andaze/layouts/partials/molecule-section-irnews-pdf-listing.html
themes/andaze/layouts/partials/organism-section-irnews-right.html
themes/andaze/layouts/partials/organism-section-news-left.html
themes/andaze/layouts/partials/organism-section-news-listing.html
themes/andaze/layouts/partials/organism-section-news-right.html
themes/andaze/layouts/partials/template-section-news.html

Before merge this PR Please first merge below pr
https://github.com/andaze/WebCorporate/pull/138
To Do
==========================

Nishidai andaze/issue139

---

content/news/demo/index.en.md
content/news/demo/index.ja.md
content/news/demo1/index.en.md
content/news/demo1/index.ja.md
themes/andaze/layouts/news/list.html
themes/andaze/layouts/partials/atom-back-to-home-button.html
themes/andaze/layouts/partials/atom-irnews-pdf-date.html
themes/andaze/layouts/partials/atom-irnews-pdf-heading.html
themes/andaze/layouts/partials/atom-irnews-pdf-text.html
themes/andaze/layouts/partials/molecule-section-irnews-pdf-listing.html
themes/andaze/layouts/partials/molecule-section-tab-list.html
themes/andaze/layouts/partials/organism-section-irnews-right.html
themes/andaze/layouts/partials/organism-section-news-left.html
themes/andaze/layouts/partials/organism-section-news-listing.html
themes/andaze/layouts/partials/organism-section-news-right.html
themes/andaze/layouts/partials/organism-section-news-tab-headers.html
themes/andaze/layouts/partials/template-section-news.html

To Do
========================================

Nishidai andaze/issue141

---

themes/andaze/assets/js/top.js
themes/andaze/layouts/partials/top.html

https://github.com/andaze/WebCorporate/issues/135
初期アニメーションの変更
リサイズのバグ除去とパーティクルサイズの調整も

Hatayuki-andaze/issue135

---

config.toml
content/news/demo/index.en.md
content/news/demo/index.ja.md
content/news/demo1/index.en.md
content/news/demo1/index.ja.md
themes/andaze/layouts/partials/atom-irnews-pdf-heading.html
themes/andaze/layouts/partials/molecule-section-tab-list.html
themes/andaze/layouts/partials/organism-section-news-listing.html
themes/andaze/layouts/partials/organism-section-news-right.html
themes/andaze/layouts/partials/organism-section-news-tab-headers.html
themes/andaze/layouts/partials/pagination.html
themes/andaze/layouts/partials/template-section-news.html

To Do
========================

Nishidai andaze/issue143

---

themes/andaze/assets/js/top.js

Hatayuki-andaze/issue151

---

themes/andaze/layouts/index.html
themes/andaze/layouts/partials/atom-irnews-button.html
themes/andaze/layouts/partials/molecule-section-irnews-buttongroup.html
themes/andaze/layouts/partials/organism-section-homepage-news-services-left.html
themes/andaze/layouts/partials/organism-section-homepage-news-services-right.html
themes/andaze/layouts/partials/template-section-irnews.html
themes/andaze/layouts/partials/template-section-newtopic.html
themes/andaze/layouts/partials/template-section.html

To Do
==========================

Nishidai andaze/issue153

---

themes/andaze/assets/js/top.js

Hatayuki-andaze/issue151_2

---

content/sitemap/_index.en.md
content/sitemap/_index.ja.md
themes/andaze/layouts/partials/atom-footer-page-title.html
themes/andaze/layouts/partials/atom-footer-sitemap-text.html
themes/andaze/layouts/partials/molecule-section-footer-pagelist.html
themes/andaze/layouts/partials/organism-section-footer-page-list.html
themes/andaze/layouts/partials/template-section-footer.html
themes/andaze/layouts/shortcodes/organism-footer-page-list.html
themes/andaze/layouts/sitemap/list.html

To Do
=========================

Nishidai andaze/issue161

---

themes/andaze/assets/js/top.js
themes/andaze/layouts/partials/top.html

Hatayuki-andaze/issue170

---

themes/andaze/assets/js/top.js

Hatayuki-andaze/issue165

---

themes/andaze/layouts/partials/molecule-navbar-menu.html
themes/andaze/layouts/partials/organism-section-navbar.html

To Do
============================

Nishidai andaze/issue180

---

themes/andaze/assets/js/effect.js
themes/andaze/assets/js/top.js

minor change of key-visual

---

content/services/ai/index.en.md
content/services/ai/index.ja.md
content/services/recruit-agency/index.en.md
content/services/recruit-agency/index.ja.md
themes/andaze/layouts/partials/atom-service-img.html

To Do
===========================

Nishidai andaze/issue193

---

themes/andaze/layouts/partials/atom-header-image.html
themes/andaze/layouts/partials/atom-header-video.html

To Do
===============================

Nishidai andaze/issue202

---

themes/andaze/layouts/work-life-balance/list.html

To Do
=========================

manage width and spacing of work life balance pages

---

config.toml

Remove work-life balance menu from navbar (just footer)

---

themes/andaze/layouts/partials/atom-back-to-top-button.html
themes/andaze/layouts/partials/atom-header-image.html
themes/andaze/layouts/partials/atom-header-video.html
themes/andaze/layouts/partials/molecule-section-footer-policy-link.html
themes/andaze/layouts/partials/organism-section-homepage-news-services-right.html
themes/andaze/layouts/partials/template-section-footer.html

To Do
=======================================

Nishidai andaze/issue216

---

config.toml
themes/andaze/layouts/partials/atom-footer-page-title.html
themes/andaze/layouts/partials/molecule-section-footer-pagelist.html
themes/andaze/layouts/partials/molecule-section-mobile-footer-pagelist.html

To Do
==============================

Nishidai andaze/issue214

---

themes/andaze/layouts/partials/molecule-services-polaroid-card.html
themes/andaze/layouts/partials/organism-section-contents.html
themes/andaze/layouts/partials/template-section.html

update border-style and width of card

update style of service component on top page

---

themes/andaze/layouts/contact/list.html
themes/andaze/layouts/partials/contact-form-en-old.html
themes/andaze/layouts/partials/contact-form-en.html
themes/andaze/layouts/partials/contact-form-ja-old.html
themes/andaze/layouts/partials/contact-form-ja.html

To Do
===============================

Nishidai andaze/issue226

---

themes/andaze/layouts/index.html
themes/andaze/layouts/partials/molecule-section-mobile-footer-pagelist.html
themes/andaze/layouts/partials/template-section-footer.html
themes/andaze/layouts/partials/template-section-newtopic.html
themes/andaze/layouts/partials/template-section.html

issue: https://github.com/andaze/WebCorporate/issues/229

update padding of component of top-page

---

themes/andaze/layouts/partials/atom-navbar-language-search.html

To Do
==========================

remove search icon from navbar

---

themes/andaze/layouts/partials/organism-section-navbar.html

issue https://github.com/andaze/WebCorporate/issues/243
・centering the position of text and logo of facebook
・add margin to the top of menu

Update style of hamburger menu

---

themes/andaze/layouts/company/list.html
themes/andaze/layouts/partials/atom-header-video.html
themes/andaze/layouts/partials/atom-video-header-title.html

issue: https://github.com/andaze/WebCorporate/issues/245
・adjust size of movie
・update margin to the bottom of button list

update style of company page

---

themes/andaze/layouts/casestudy/list.html
themes/andaze/layouts/partials/atom-header-video.html
themes/andaze/layouts/reason/list.html
themes/andaze/layouts/services/list.html
themes/andaze/layouts/solution/list.html

issue: https://github.com/andaze/WebCorporate/issues/248
・update of video section for bottom-page

update size of video section

---

themes/andaze/layouts/casestudy/list.html
themes/andaze/layouts/partials/template-section-news.html
themes/andaze/layouts/reason/list.html
themes/andaze/layouts/services/list.html
themes/andaze/layouts/solution/list.html
themes/andaze/layouts/work-life-balance/list.html

issue: https://github.com/andaze/WebCorporate/issues/250

update margin for contents of bottom-page

---

themes/andaze/assets/js/top-sub.js
themes/andaze/layouts/index.html
themes/andaze/layouts/partials/atom-section-company-main-text.html
themes/andaze/layouts/partials/atom-section-company-sub-text.html
themes/andaze/layouts/partials/molecule-section-company-texts.html
themes/andaze/layouts/partials/molecule-section-irnews-buttongroup.html
themes/andaze/layouts/partials/organism-section-homepage-company.html
themes/andaze/layouts/partials/template-section-company.html

issue: https://github.com/andaze/WebCorporate/issues/252
・create section io top-page

create section on top-page for accessing to company-page

---

themes/andaze/layouts/partials/atom-recruit-text.html

issue: https://github.com/andaze/WebCorporate/issues/255

Change text for recruit section on top page

---

themes/andaze/layouts/partials/atom-footer-page-title.html

issue: https://github.com/andaze/WebCorporate/issues/258

enable to access to recruit site rom footer-nav

---

themes/andaze/layouts/partials/atom-footer-facebook-icon.html
themes/andaze/layouts/partials/atom-irnews-button.html
themes/andaze/layouts/partials/atom-navbar-menu-list.html
themes/andaze/layouts/partials/molecule-section-irnews-pdf-listing.html
themes/andaze/layouts/partials/molecule-section-share-social-media-link.html

issue: https://github.com/andaze/WebCorporate/issues/260

 add [rel="noopener noreferrer"] to link-tag with option [target="_blank"]

---

config.toml
themes/andaze/layouts/partials/contact-form-en.html
themes/andaze/layouts/partials/contact-form-ja.html

To Do
=============================

Nishidai andaze/issue219

---

config.toml

To Do
=================================

update secure token form mail

---

config.toml
themes/andaze/layouts/partials/contact-form-en.html
themes/andaze/layouts/partials/contact-form-ja.html

Nishidai andaze/issue266

---

themes/andaze/assets/css/tailwind.css
themes/andaze/layouts/partials/molecule-section-tab-list.html
themes/andaze/layouts/partials/organism-section-news-listing.html

To Do
===============================

Nishidai andaze/issue240

---

themes/andaze/layouts/partials/molecule-section-footer-pagelist.html
themes/andaze/layouts/partials/molecule-section-mobile-footer-pagelist.html

To Do
===========================

Nishidai andaze/issue239

---

themes/andaze/layouts/partials/atom-irnews-button.html
themes/andaze/layouts/partials/molecule-section-irnews-buttongroup.html
themes/andaze/layouts/partials/template-section-recruit.html

issue: https://github.com/andaze/WebCorporate/issues/276

enable to access to recruit site from section on top-page

---

config.toml
themes/andaze/layouts/partials/contact-form-en.html
themes/andaze/layouts/partials/contact-form-ja.html

Nishidai andaze/issue274

---

config.toml
content/solution/_index.ja.md
themes/andaze/layouts/_default/baseof.html
themes/andaze/layouts/partials/molecule-section-mobile-footer-pagelist.html
themes/andaze/layouts/partials/organism-section-homepage-company.html
themes/andaze/layouts/partials/tailwindcss.cdn.html

・loading for key-visual
・text of solution
・footer of mobile end
・width of company contents on top-page

Style update

---

themes/andaze/assets/js/swup.js
themes/andaze/assets/js/top-sub.js
themes/andaze/assets/js/top.js

issue: https://github.com/andaze/WebCorporate/issues/282

remove loading effect on bottom-page

---

themes/andaze/layouts/index.html
themes/andaze/layouts/partials/template-section-newtopic.html

Add logic: toggle show/hidden sections

---

themes/andaze/assets/js/swup.js
themes/andaze/assets/js/top-sub.js
themes/andaze/layouts/_default/baseof.html

remove loading screen
issue: https://github.com/andaze/WebCorporate/issues/298

enable to click link

---

content/casestudy/case1/index.en.md
content/casestudy/case1/index.ja.md
content/casestudy/case2/index.en.md
content/casestudy/case3/index.en.md
content/casestudy/case4/index.en.md
content/casestudy/case5/index.en.md
content/casestudy/case6/index.en.md
content/company/about/index.en.md
content/quality/_index.en.md
content/security/_index.en.md
content/services/ai/index.en.md
content/services/cloud/index.en.md
content/services/consulting/index.en.md
content/services/design/index.en.md
content/services/recruit-agency/index.en.md
content/services/service-develop/index.en.md
content/services/shared/index.en.md
content/work-life-balance/_index.en.md
themes/andaze/layouts/partials/atom-back-button.html

issue: https://github.com/andaze/WebCorporate/issues/296

Add English contents

---

themes/andaze/layouts/partials/atom-service-title.html
themes/andaze/layouts/partials/molecule-services-polaroid-card.html
themes/andaze/layouts/partials/organism-section-contents.html

issue: https://github.com/andaze/WebCorporate/issues/303

update style of cards

---

themes/andaze/assets/css/tailwind.css
themes/andaze/layouts/company/list.html
themes/andaze/layouts/partials/breadcrumbs.html

To Do
=============================

Nishidai andaze/issue305

---

config.toml

issue: https://github.com/andaze/WebCorporate/issues/311

fix url to casestudy-page

---

themes/andaze/assets/js/top.js

issue: https://github.com/andaze/WebCorporate/issues/314

particles gather after fade in

---

themes/andaze/layouts/partials/atom-footer-copyright-text.html

issue: https://github.com/andaze/WebCorporate/issues/318

update copyright text

---

content/company/about/index.en.md
content/company/about/index.ja.md

issue: https://github.com/andaze/WebCorporate/issues/320

update design of about-page to table style

---

config.toml

issue: https://github.com/andaze/WebCorporate/issues/322

update texts of menu for mobile in English

---

content/company/history/index.en.md
content/company/history/index.ja.md

issue: https://github.com/andaze/WebCorporate/issues/324

update design of history-page

---

themes/andaze/assets/js/swup.js
themes/andaze/layouts/partials/atom-header-image.html
themes/andaze/layouts/partials/atom-image-header-title.html

when we on top-message page, set object-position of header right
adjust header title position

update header image position

---

themes/andaze/layouts/partials/molecule-section-company-detailpage-buttonlist.html

issue: https://github.com/andaze/WebCorporate/issues/308

update design of company list page

---

content/_index.en.md
content/_index.ja.md
themes/andaze/assets/css/tailwind.css
themes/andaze/layouts/partials/organism-section-homepage-company.html

・update padding
・add new line to texts
・remove underline from texts

Update design for top of home page

---

themes/andaze/layouts/index.html
themes/andaze/layouts/partials/organism-section-homepage-news-services-right.html

if number of cards on home-page increase, site may look like DIP
so, add contents of solution to top-page to increase number of cards

add section to home page

---

config.toml

navbar menu order

---

themes/andaze/layouts/partials/organism-section-homepage-news-services-right.html

mistake from resolving conflict

remove casestudy doubled from home page

---

themes/andaze/layouts/partials/atom-irnews-heading.html
themes/andaze/layouts/partials/template-section-recruit.html

Update design of recruit section on home page

---

themes/andaze/layouts/index.html

centering the position

---

themes/andaze/assets/css/tailwind.css
themes/andaze/layouts/_default/baseof.html

Update space between characters

---

themes/andaze/assets/js/swup.js
themes/andaze/assets/js/top-sub.js
themes/andaze/assets/js/top.js

Change logic flow for key visual

---

themes/andaze/assets/js/swiper.js

Make browser not reload with resizing

---

themes/andaze/layouts/partials/atom-irnews-button.html

update style of button on top page

---

themes/andaze/assets/js/top-sub.js
themes/andaze/assets/js/top.js

Enable to swipe particles every time on top of page

---

themes/andaze/layouts/partials/atom-irnews-button.html

update button style on top page again

---

themes/andaze/layouts/partials/atom-white-transparent-top-text-main.html
themes/andaze/layouts/partials/molecule-card-with-text.html
themes/andaze/layouts/partials/organism-section-cards-part.html
themes/andaze/layouts/partials/tailwindcss.cdn.html
themes/andaze/layouts/reason/list.html

update alignment of service card on home page and reason page

---

themes/andaze/assets/js/top-sub.js
themes/andaze/assets/js/top.js

update timing of animation start on key visual

---

themes/andaze/layouts/partials/atom-picture.html
themes/andaze/layouts/partials/molecule-card-with-text.html
themes/andaze/layouts/reason/list.html
themes/andaze/layouts/shortcodes/picture.html

Nishidai-andaze/issue481

---

content/company/about/index.ja.md

fix company text

---

themes/andaze/assets/js/swiper.js
themes/andaze/assets/js/swup.js
themes/andaze/assets/js/top.js

fix_mobile_resize_error

---

themes/andaze/layouts/partials/atom-image-header-title.html
themes/andaze/layouts/partials/molecule-section-company-detailpage-buttonlist.html

fix color and UI break

---

themes/andaze/layouts/partials/template-section-footer.html

update padding-top of footer

---

themes/andaze/layouts/partials/script-mainjs.html

fix JS bug

---

.github/workflows/gh-pages.yml

LPのURLをとる（優先）

---

themes/andaze/layouts/partials/molecule-card-with-text.html

update height of card for service

---

themes/andaze/assets/js/swiper.js
themes/andaze/assets/js/youtube.js
themes/andaze/layouts/partials/organism-section-homepage-news-services-right.html
themes/andaze/layouts/partials/template-section-youtube.html

Fix youtube swiper bug

---

config.toml
themes/andaze/layouts/index.html

Update space on top of home page

---

themes/andaze/layouts/partials/organism-section-homepage-news-services-right.html

update position of modal

---

themes/andaze/layouts/partials/molecule-services-polaroid-card.html

update solution card

---

content/company/about/index.en.md

update address text EN

---

themes/andaze/layouts/index.html
themes/andaze/layouts/partials/organism-section-contents.html
themes/andaze/layouts/partials/organism-section-homepage-news-services-left.html
themes/andaze/layouts/partials/organism-section-homepage-news-services-right.html
themes/andaze/layouts/partials/template-section-newtopic.html
themes/andaze/layouts/partials/template-section-youtube.html
themes/andaze/layouts/partials/template-section.html

Update section style for responsiveness

---

themes/andaze/assets/js/main.js
themes/andaze/assets/js/swiper.js
themes/andaze/layouts/services/single.html

Create solution slider

---

themes/andaze/assets/js/main.js

fix js import bug

---

themes/andaze/layouts/partials/contact-form-en.html
themes/andaze/layouts/partials/contact-form-ja.html

add lead text above the contact form

---

themes/andaze/assets/js/top.js
themes/andaze/layouts/partials/top.html

update key-visual code

---

content/download.en.md
content/download.ja.md
themes/andaze/layouts/partials/atom-download-button.html
themes/andaze/layouts/services/single.html
themes/andaze/layouts/shortcodes/download-button.html

add ebook section to service single page

---

themes/andaze/assets/js/main.js
themes/andaze/assets/js/top.js
themes/andaze/layouts/partials/top.html

Separate top.js

---

themes/andaze/layouts/blogs/section.html
themes/andaze/layouts/partials/atom/button.html

fixed https://github.com/andaze/WebCorporate/issues/723
fixed https://github.com/andaze/WebCorporate/issues/741

741 blogs ディレクトリファイル構造を変更する

---

themes/andaze/assets/js/main.js
themes/andaze/assets/js/sendform.js
themes/andaze/layouts/partials/contact-form-en.html
themes/andaze/layouts/partials/contact-form-ja.html

Fix contact form

---

themes/andaze/assets/js/main.js
themes/andaze/layouts/partials/atom-download-button.html

Update download method

---

config.yaml
content/recruit/_index.en.md
themes/andaze/layouts/index.html
themes/andaze/layouts/partials/atom-footer-page-title.html
themes/andaze/layouts/partials/atom-irnews-heading.html
themes/andaze/layouts/partials/atom-navbar-menu-list.html
themes/andaze/layouts/partials/organism-section-navbar.html

Change menu from recruit to careers

---

themes/andaze/assets/js/top.js

-[ ] aタグをクリックするとmeshを削除する処理を無効化（SWUPを使わないなら必要ない処理）

deactivate removeMesh function

---

themes/andaze/assets/js/top.js
themes/andaze/layouts/index.html

Update to fix key visual bug

---

content/download.en.md
content/download.ja.md

hide download from footer menu list

---

themes/andaze/layouts/partials/molecule-card-with-text.html
themes/andaze/layouts/partials/organism-section-cards-part.html

-----------------------------------

Update design of service card on top page

---

themes/andaze/assets/js/top.js

Code optimization for key-visual

---

content/download.en.md
content/download.ja.md
themes/andaze/layouts/index.html
themes/andaze/layouts/partials/atom-download-button.html
themes/andaze/layouts/partials/atom-irnews-button.html
themes/andaze/layouts/services/single.html
themes/andaze/layouts/shortcodes/download-button.html

refactoring button template

---

content/download.en.md
content/download.ja.md
themes/andaze/layouts/index.html
themes/andaze/layouts/partials/atom-header-video-random.html
themes/andaze/layouts/partials/header.html
themes/andaze/layouts/partials/molecule-section-header-image.html
themes/andaze/layouts/partials/molecule-section-header-video.html
themes/andaze/layouts/partials/organism-page-header-with-media.html
themes/andaze/layouts/partials/organism-section-contents.html
themes/andaze/layouts/partials/template-section.html

update responsive styling for large screen width

---

themes/andaze/assets/js/swiper.js

adjust swiper behavior

---

themes/andaze/layouts/partials/article.html
themes/andaze/layouts/partials/molecule-card-with-text.html
themes/andaze/layouts/partials/organism-section-contents.html
themes/andaze/layouts/partials/organism-service-header.html
themes/andaze/layouts/services/single.html
themes/andaze/layouts/solution/single.html

Remove subtitle and update styling

---

themes/andaze/assets/css/tailwind.css

fix table size
